"""SentiSense — Official Python SDK for the SentiSense market intelligence API."""

from sentisense.__about__ import __version__
from sentisense.client import SentiSenseClient
from sentisense.exceptions import (
    APIError,
    AuthenticationError,
    NotFoundError,
    RateLimitError,
    SentiSenseError,
)
from sentisense.types import (
    ClusterBuy,
    CongressTrade,
    Document,
    DocumentSearchResponse,
    Insight,
    InsightDocRef,
    InsiderActivity,
    InsiderActivitySummary,
    InsiderTrade,
    InstitutionalFlow,
    InstitutionalFlows,
    MarketStatus,
    MarketSummary,
    PoliticianDetail,
    PoliticianSummary,
    PreviewResult,
    Quarter,
    SentimentEntry,
    SimilarStock,
    StockDetail,
    StockPrice,
    Story,
    StoryCluster,
)

__all__ = [
    "__version__",
    "APIError",
    "AuthenticationError",
    "ClusterBuy",
    "CongressTrade",
    "Document",
    "DocumentSearchResponse",
    "Insight",
    "InsightDocRef",
    "InsiderActivity",
    "InsiderActivitySummary",
    "InsiderTrade",
    "InstitutionalFlow",
    "InstitutionalFlows",
    "MarketStatus",
    "MarketSummary",
    "NotFoundError",
    "PoliticianDetail",
    "PoliticianSummary",
    "PreviewResult",
    "Quarter",
    "RateLimitError",
    "SentiSenseClient",
    "SentiSenseError",
    "SentimentEntry",
    "SimilarStock",
    "StockDetail",
    "StockPrice",
    "Story",
    "StoryCluster",
]
